<?php
/*********************************\ 
SETTINGS v1.0.18.1&psi;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$version = "3.01";
$settings['logo'] = "/img/logo.png";
$settings['gamelocation'] = "/user/games";
$settings['adminemail'] = "someone@somewhere.co.uk";
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "someone@somewhere.co.uk"; // future expansion
$settings['siteclosed'] = "0";
$settings['siteclosed_url'] = "/closed.html";
$settings['pwdlen'] = "3";
$settings['https'] = "1";
$settings['url'] = "https://api.noideersoftware.co.uk";
$settings['steamkey'] = "";
$settings['SQ_TIMEOUT'] = 2; // timeout for game server queries
$settings['year'] = false; // set to 1 if you want dates in roman numerals
$settings['start_year'] = "2014";
$settings['time_format'] = "h:i:s a";
$settings['date_format'] = "d/m/Y";
$settings['login'] = "1";
$settings['ip_key'] ='14a382cdc7db50e856bd3f181ed45b585a58c858b4785c0dae4fa27f'; // your data key for ipdata.io
$settings['scanlog'] = 1;
$settings['send_cors'] = 0; // send cors headers or not 0 = not 1 = send header
$settings['secure_user'] ='jerry'; // ajax secure user
$settings['secure_password']='hello'; // ajax secure password
$settings['mux'] = "screen"; // set to tmux if you want to use tmux
$settings['router_ip'] = true; // show all router ip's in the list
$settings['use_git'] = true; // use git for the file structure & update check require git to be installed. Useful for developers 
$settings['branch'] = "v3"; // which branch to use
$settings['install_updates'] = true;  // if use_git is true update the files or not
$settings['save_updates'] = true; // if use_git is false save the updates no effect if use_git = true  
?>
